### ISSUE TITLE
FAST Fortrant does not load the metamodel generator

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/FAST-Fortran#118]
I tried to load FAST Fortran as described in the README but this leads to an unclean load because the generator is missing the superclass. 

It seems that the baseline does not load the generator of FAST core.

**Comment by NicolasAnquetil** [comment]
the issue probably comes from [https://github.com/moosetechnology/FAST/issues/38](https://github.com/moosetechnology/FAST/issues/38)

**Comment by NicolasAnquetil** [comment]
fixed in BaselineOfFAST
