### ISSUE TITLE
parameters are duplicated in FastFortranSubroutine and FastFortranFunction

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-Fortran#28]
for example 'findbk' has 4 parameters: lib, title, lib, title

**Comment by NicolasAnquetil** [comment]
to check, doe snot seem to happen anymore, may be there was a bug in the import ...

**Comment by lsafina** [comment]
tested on "testFunctionWithParameter" and "testSubroutineWithParameters. Not reproducible
