### ISSUE TITLE
do we need FASTFortranTNamedBehaviouralEntity ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-Fortran#33]
We could used TBehaviouralEntity + TNamedEntity

Note: Same discussion applies to all of FAST (Java, Pharo)

**Comment by lsafina** [comment]
merged

**Comment by lsafina** [comment]
TNamedBehaviouralEntity exists at the moment as it being created by "super defineTraits" creating copy of all FAST traits tailored for the project and can not be deleted separately. However, it will disappear as soon as we start to use FAST traits instead of fortran ones

**Comment by NicolasAnquetil** [comment]
Great, let's create an issue for that ... and do it :-)
