### ISSUE TITLE
Arguments of FASTFortranWriteStatement appear to be duplicated

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-Fortran#34]
for example:
```fortran
      write(*,*) 'borbk: begin'
```
has 2 arguments: 2 FASTFortranCharacterLiteral with same #primitveValue

Could be related to #28

**Comment by lsafina** [comment]
testStatementCallWrite produces 1 argument but there is something weird going on, need to check further

**Comment by NicolasAnquetil** [comment]
seems to be corrected
could not reproduce
