### ISSUE TITLE
What's the use of FASTFortranTFortranBinaryExpression ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-Fortran#37]
since operator/left//right are defined in FASTFortranBinaryExpression, why having a trait ?

**Comment by NicolasAnquetil** [comment]
That is correct: cannot instantiate a Trait

I prefer (a): put left/right in `TBinaryExpression` and have `FortranBinaryExpression` "inherit" them from the trait
There is also a need for an `operator` in `TBinaryExpression`.
It can be just a `String` for now.

**Comment by lsafina** [comment]
move left/right, operator from unary/binary expressions to the traits level
merged
