### ISSUE TITLE
Init part of LoopControlExpression should not be a statement

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-Fortran#38]
currently #init of a LoopControlExpression is an AssignmentStatement
It should be an AssignementExpression
Tjis implies:
- creating FASTFortranAssignementExpression class as a copy of AssignementStatement
- changing AssignementStatement to contain an AssignementExpression ?

**Comment by lsafina** [comment]
merged pull#59
- Created an entity `FastFortranAssignmentExpression` that has `leftPart` and `rightPart` of `FastFortranVariable`.
- Change type of `init` in `loopControlExpression` to `FastFortranAssignmentExpression`
