### ISSUE TITLE
what are FASTFortranPointer, FASTFortranRecord, FASTFortranStructure ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-Fortran#48]
Belongs to FAST-Esope ?

**Comment by NicolasAnquetil** [comment]
If we don't need them, let's remove them for now.
Better to keep the meta-model as minimal as possible.
Having them without knowing what they do or being able to import them is no use anyway.

**Comment by lsafina** [comment]
merged
